trigger:
  - 408_performance_improvement_migration

variables:
  CODECOV_TOKEN: 504b0637-b4c1-4991-bc79-7a29aee41b44
  CIBW_BUILD: cp36-* cp37-* cp38-*
  CIBW_BEFORE_BUILD: python -m pip install --upgrade pip

jobs:
- job: MacOS_Test_py37
  pool: {vmImage: 'macos-latest'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        python -m pip install numba
        python -m pip install .[dev] codecov
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
